import 'package:legalease_matrimonial/src/pages/contents/categories_contents/categories_sections/statutory_rights/republic_8424/statutory_1-13.dart';
import 'package:legalease_matrimonial/src/pages/contents/categories_contents/categories_sections/statutory_rights/republic_881/aritcle_IV/article_4.dart';
import 'package:legalease_matrimonial/src/pages/contents/categories_contents/categories_sections/statutory_rights/republic_881/article_I/article_1.dart';
import 'package:legalease_matrimonial/src/pages/contents/categories_contents/categories_sections/statutory_rights/republic_881/article_II/article_2.dart';
import 'package:legalease_matrimonial/src/pages/contents/categories_contents/categories_sections/statutory_rights/republic_881/article_III/article_3.dart';
import 'package:legalease_matrimonial/src/pages/contents/categories_contents/categories_sections/statutory_rights/republic_881/article_IX/article_9.dart';
import 'package:legalease_matrimonial/src/pages/contents/categories_contents/categories_sections/statutory_rights/republic_881/article_V/article_5.dart';
import 'package:legalease_matrimonial/src/pages/contents/categories_contents/categories_sections/statutory_rights/republic_881/article_VI/article_6.dart';
import 'package:legalease_matrimonial/src/pages/contents/categories_contents/categories_sections/statutory_rights/republic_881/article_VII/article_7.dart';
import 'package:legalease_matrimonial/src/pages/contents/categories_contents/categories_sections/statutory_rights/republic_881/article_VIII/article_8.dart';
import 'package:legalease_matrimonial/src/pages/contents/categories_contents/categories_sections/statutory_rights/republic_881/article_X/article_10.dart';
import 'package:legalease_matrimonial/src/pages/contents/categories_contents/categories_sections/statutory_rights/republic_881/article_XI/article_11.dart';
import 'package:legalease_matrimonial/src/pages/contents/categories_contents/categories_sections/statutory_rights/republic_881/article_XII/article_12.dart';
import 'package:legalease_matrimonial/src/pages/contents/categories_contents/categories_sections/statutory_rights/republic_881/article_XIII/article_13.dart';
import 'package:legalease_matrimonial/src/pages/contents/categories_contents/categories_sections/statutory_rights/republic_881/article_XIV/article_14.dart';
import 'package:legalease_matrimonial/src/pages/contents/categories_contents/categories_sections/statutory_rights/republic_881/article_XIX/article_19.dart';
import 'package:legalease_matrimonial/src/pages/contents/categories_contents/categories_sections/statutory_rights/republic_881/article_XV/article_15.dart';
import 'package:legalease_matrimonial/src/pages/contents/categories_contents/categories_sections/statutory_rights/republic_881/article_XVI/article_16.dart';
import 'package:legalease_matrimonial/src/pages/contents/categories_contents/categories_sections/statutory_rights/republic_881/article_XVII/article_17.dart';
import 'package:legalease_matrimonial/src/pages/contents/categories_contents/categories_sections/statutory_rights/republic_881/article_XVIII/article_18.dart';
import 'package:legalease_matrimonial/src/pages/contents/categories_contents/categories_sections/statutory_rights/republic_881/article_XX/article_20.dart';
import 'package:legalease_matrimonial/src/pages/contents/categories_contents/categories_sections/statutory_rights/republic_881/article_XXI/article_21.dart';
import 'package:legalease_matrimonial/src/pages/contents/categories_contents/categories_sections/statutory_rights/republic_881/article_XXII/article_22.dart';
import 'package:legalease_matrimonial/src/pages/contents/categories_contents/categories_sections/statutory_rights/republic_881/article_XXIII/article_23.dart';
import 'package:legalease_matrimonial/src/pages/contents/categories_contents/categories_sections/statutory_rights/republic_881/article_XXIV/article_24.dart';
import 'package:legalease_matrimonial/src/pages/contents/categories_contents/categories_sections/statutory_rights/republic_881/article_XXV/article_25.dart';
import 'package:legalease_matrimonial/src/pages/contents/categories_contents/categories_sections/statutory_rights/republic_881/section_contents/section-101-200.dart';
import 'package:legalease_matrimonial/src/pages/contents/categories_contents/categories_sections/statutory_rights/republic_881/section_contents/section_1-50.dart';
import 'package:legalease_matrimonial/src/pages/contents/categories_contents/categories_sections/statutory_rights/republic_881/section_contents/section_201-283.dart';
import 'package:legalease_matrimonial/src/pages/contents/categories_contents/categories_sections/statutory_rights/republic_881/section_contents/section_51-100.dart';

import 'inchoate_sections.dart';

// republic act 8424
class ListOfSectionsStatutory {
  static List<Sections> statutorySection = [
    Sections(title: 'Section 1', description: 'Definition of Terms'),
    Sections(title: 'Section 2', description: 'Accreditation of non-stock, non-profit corporations/NGOs by the Accrediting Entity'),
    Sections(title: 'Section 3', description: 'Donations to Accredited Non-stock, Non-profit Corporations/NGOs'),
    Sections(title: 'Section 4', description: 'Utilization Requirements'),
    Sections(title: 'Section 5', description: 'Certificate of Donations'),
    Sections(title: 'Section 6', description: 'Notice of Donations'),
    Sections(title: 'Section 7', description: 'Date and Place of Filing Returns'),
    Sections(title: 'Section 8', description: 'Substantiation Requirements'),
    Sections(title: 'Section 9', description: 'Monitoring and Verification of Annual Information Return'),
    Sections(title: 'Section 10', description: 'Prohibited Transactions'),
    Sections(title: 'Section 11', description: 'Withdrawal of Certificate of Accreditation and Revocation of the Certificate of Registration'),
    Sections(title: 'Section 12', description: 'Repealing Clause'),
    Sections(title: 'Section 13', description: 'Effectivity'),
  ];

}

class ListOfRoutesStatutory {
  static List statutoryRoutes = const [
    StatutoryOne(),
    StatutoryTwo(),
    StatutoryThree(),
    StatutoryFour(),
    StatutoryFive(),
    StatutorySix(),
    StatutorySeven(),
    StatutoryEight(),
    StatutoryNine(),
    StatutoryTen(),
    StatutoryEleven(),
    StatutoryTwelve(),
    StatutoryThirteen(),
  ];
}


// republic act 881
class ListOfArticlesStatutory {
  
  static List<Sections> listArticles = [
    Sections(title: 'Aricle I', description: 'GENERAL PROVISIONS'),
    Sections(title: 'Aricle II', description: 'ELECTION OF PRESIDENT AND VICE-PRESIDENT'),
    Sections(title: 'Aricle III', description: 'ELECTION OF MEMBERS OF THE BATASANG PAMBANSA'),
    Sections(title: 'Aricle IV', description: 'ELECTION OF LOCAL OFFICIALS'),
    Sections(title: 'Aricle V', description: 'ELECTION OF MEMBERS OF THE REGIONAL ASSEMBLY OF THE AUTONOMOUS REGIONS'),
    Sections(title: 'Aricle VI', description: 'ELECTION OF BARANGAY OFFICIALS'),
    Sections(title: 'Aricle VII', description: 'THE COMMISSION ON ELECTIONS'),
    Sections(title: 'Aricle VIII', description: 'POLITICAL PARTIES'),
    Sections(title: 'Aricle IX', description: 'ELIGIBILITY OF CANDIDATES AND CERTIFICATE OF CANDIDACY'),
    Sections(title: 'Aricle X', description: 'CAMPAIGN AND ELECTION PROPAGANDA'),
    Sections(title: 'Aricle XI', description: 'ELECTORAL CONTRIBUTIONS AND EXPENDITURES'),
    Sections(title: 'Aricle XII', description: 'REGISTRATION OF VOTERS'),
    Sections(title: 'Aricle XIII', description: 'PRECINCTS AND POLLING PLACES'),
    Sections(title: 'Aricle XIV', description: 'BOARD OF ELECTION INSPECTORS'),
    Sections(title: 'Aricle XV', description: 'WATCHERS'),
    Sections(title: 'Aricle XVI', description: 'OFFICIAL BALLOTS AND ELECTION RETURNS'),
    Sections(title: 'Aricle XVII', description: 'CASTING OF VOTES'),
    Sections(title: 'Aricle XVIII', description: 'COUNTING OF VOTES'),
    Sections(title: 'Aricle XIX', description: 'CANVASS AND PROCLAMATION'),
    Sections(title: 'Aricle XX', description: 'PRE-PROCLAMATION CONTROVERSIES'),
    Sections(title: 'Aricle XXI', description: 'ELECTION CONTESTS'),
    Sections(title: 'Aricle XXII', description: 'ELECTION OFFENSES'),
    Sections(title: 'Aricle XXIII', description: 'LEGAL FEES'),
    Sections(title: 'Aricle XXIV', description: 'TRANSITORY PROVISIONS'),
    Sections(title: 'Aricle XXV', description: 'FINAL PROVISIONS'),
  ];


  static List<Sections> sections881 = [
    Sections(title: 'Section 1', description: 'Title'),
    Sections(title: 'Section 2', description: 'Applicability'),
    Sections(title: 'Section 3', description: 'Election  and  campaign  periods'),
    Sections(title: 'Section 4', description: 'Obligation to register and vote'),
    Sections(title: 'Section 5', description: 'Postponement of election'),
    Sections(title: 'Section 6', description: 'Failure of election'),
    Sections(title: 'Section 7', description: 'Call of special election'),
    Sections(title: 'Section 8', description: 'Election Code to be available in polling places'),
    Sections(title: 'Section 9', description: 'Official mail and telegram relative to elections'),
    Sections(title: 'Section 10', description: 'Election  expenses'),
    Sections(title: 'Section 11', description: 'Failure to assume office'),
    Sections(title: 'Section 12', description: 'Disqualifications'),
    Sections(title: 'Section 13', description: 'Regular election for President and Vice-President'),
    Sections(title: 'Section 14', description: 'Special election for President and Vice-President'),
    Sections(title: 'Section 15', description: 'Canvass of votes for President and Vice-President by the provincial or city board of canvassers'),
    Sections(title: 'Section 16', description: 'Counting of votes for President and Vice-President by the Batasang Pambansa'),
    Sections(title: 'Section 17', description: 'Correction of errors in certificate and supporting statement already  transmitted to the Speaker'),
    Sections(title: 'Section 18', description: 'Preservation of ballot boxes, their keys, and disposition of their contents'),
    Sections(title: 'Section 19', description: 'When certificate of  canvass is incomplete or bears erasures or alterations'),
    Sections(title: 'Section 20', description: 'Proclamation of the President-elect and Vice-President-elect'),
    Sections(title: 'Section 21', description: 'Regular election of Members of the Batasang Pambansa'),
    Sections(title: 'Section 22', description: 'Special election for Members of the Batasang Pambansa'),
    Sections(title: 'Section 23', description: 'Composition of the Batasang Pambansa'),
    Sections(title: 'Section 24', description: 'Apportionment of representatives'),
    Sections(title: 'Section 25', description: 'Voting by province and its component cities, by highly urbanized city or by district in Metropolitan Manila'),
    Sections(title: 'Section 26', description: 'Sectoral representatives'),
    Sections(title: 'Section 27', description: 'Scope of the sectors'),
    Sections(title: 'Section 28', description: 'Selection of sectoral representatives'),
    Sections(title: 'Section 29', description: 'Regular  elections  of  local  officials'),
    Sections(title: 'Section 30', description: 'Component  and  highly  urbanized  cities'),
    Sections(title: 'Section 31', description: 'The  Sangguniang  Pampook  of  the  autonomous  regions'),
    Sections(title: 'Section 32', description: 'Apportionment  of  members  of  the  Sangguniang  Pampook'),
    Sections(title: 'Section 33', description: 'Election  of  members  of  Sangguniang  Pampook'),
    Sections(title: 'Section 34', description: 'Selection  of  sectoral  representatives'),
    Sections(title: 'Section 35', description: 'Filling of vacancy'),
    Sections(title: 'Section 36', description: 'Term of office'),
    Sections(title: 'Section 37', description: 'Regular election of barangay officials'),
    Sections(title: 'Section 38', description: 'Conduct  of  elections'),
    Sections(title: 'Section 39', description: 'Certificate of Candidacy'),
    Sections(title: 'Section 40', description: 'Board of Election Tellers'),
    Sections(title: 'Section 41', description: 'Registration of voters and list of voters'),
    Sections(title: 'Section 42', description: 'Polling places'),
    Sections(title: 'Section 43', description: 'Official  barangay  ballots'),
    Sections(title: 'Section 44', description: 'Ballot boxes'),
    Sections(title: 'Section 45', description: 'Postponement or failure of election'),
    Sections(title: 'Section 46', description: 'Barangay board of canvassers'),
    Sections(title: 'Section 47', description: 'Activities during the campaign period'),
    Sections(title: 'Section 48', description: 'Watchers'),
    Sections(title: 'Section 49', description: 'Inclusion and exclusion cases'),
    Sections(title: 'Section 50', description: 'Funding'),
    Sections(title: 'Section 51', description: 'Penalties'),
    Sections(title: 'Section 52', description: ' Powers  and  functions  of  the  Commission  on  Elections'),
    Sections(title: 'Section 53', description: 'Field offices of the Commission'),
    Sections(title: 'Section 54', description: 'Qualifications'),
    Sections(title: 'Section 55', description: 'Office  space'),
    Sections(title: 'Section 56', description: 'Changes in the composition, distribution or assignment of field offices'),
    Sections(title: 'Section 57', description: 'Measures to ensure enforcement'),
    Sections(title: 'Section 58', description: 'Disqualifications  of  members  of  the  Commission'),
    Sections(title: 'Section 59', description: 'Publication of official ballots and election returns and printing thereof'),
    Sections(title: 'Section 60', description: 'Political party'),
    Sections(title: 'Section 61', description: 'Registration'),
    Sections(title: 'Section 62', description: 'Publication of petition for registration or accreditation'),
    Sections(title: 'Section 63', description: 'Qualifications  for  President  and  Vice-President  of  the  Philippines'),
    Sections(title: 'Section 64', description: 'Qualifications for Members of the Batasang Pambansa'),
    Sections(title: 'Section 65', description: 'Qualifications of elective local officials'),
    Sections(title: 'Section 66', description: 'CCandidates  holding  appointive  office  or  positions'),
    Sections(title: 'Section 67', description: 'Candidates holding elective office'),
    Sections(title: 'Section 68', description: 'Disqualifications'),
    Sections(title: 'Section 69', description: 'Nuisance candidates'),
    Sections(title: 'Section 70', description: 'Guest candidacy'),
    Sections(title: 'Section 71', description: ''),
    Sections(title: 'Section 72', description: 'Effects of disqualification cases and priority'),
    Sections(title: 'Section 73', description: 'Certificate  of  candidacy'),
    Sections(title: 'Section 74', description: 'Contents of certificate of candidacy'),
    Sections(title: 'Section 75', description: 'Filing and distribution of certificate of candidacy'),
    Sections(title: 'Section 76', description: 'Ministerial  duty  of  receiving  and  acknowledging  receipt'),
    Sections(title: 'Section 77', description: 'Candidates in case of death, disqualification or withdrawal of another'),
    Sections(title: 'Section 78', description: 'Petition to deny due course to or cancel a certificate of candidacy'),
    Sections(title: 'Section 79', description: 'Definitions'),
    Sections(title: 'Section 80', description: 'Election campaign or partisan political activity outside campaign period'),
    Sections(title: 'Section 81', description: 'ntervention of foreigners'),
    Sections(title: 'Section 82', description: 'Lawful election propaganda'),
    Sections(title: 'Section 83', description: 'Removal, destruction or defacement of lawful election propaganda prohibited'),
    Sections(title: 'Section 84', description: 'Requirements for published or printed election propaganda'),
    Sections(title: 'Section 85', description: 'Prohibited forms of election propaganda'),
    Sections(title: 'Section 86', description: 'Regulation of election propaganda through mass media'),
    Sections(title: 'Section 87', description: 'Rallies, meetings and other political activities'),
    Sections(title: 'Section 88', description: 'Public rally'),
    Sections(title: 'Section 89', description: 'Transportation, food and drinks'),
    Sections(title: 'Section 90', description: 'Comelec space'),
    Sections(title: 'Section 91', description: 'Comelec poster area'),
    Sections(title: 'Section 92', description: 'Comelec  time'),
    Sections(title: 'Section 93', description: 'Comelec  information  bulletin'),
    Sections(title: 'Section 94', description: 'Definitions'),
    Sections(title: 'Section 95', description: 'Prohibited  contributions'),
    Sections(title: 'Section 96', description: 'Soliciting or receiving contributions from foreign sources'),
    Sections(title: 'Section 97', description: 'Prohibited raising of funds'),
    Sections(title: 'Section 98', description: 'True name of contributor required'),
    Sections(title: 'Section 99', description: 'Report of contributions'),
    Sections(title: 'Section 100', description: 'Limitations upon expenses of candidates'),
    Sections(title: 'Section 101', description: 'Limitations upon expenses of political parties'),
    Sections(title: 'Section 102', description: 'Lawful expenditures'),
    Sections(title: 'Section 103', description: 'Persons authorized to incur election expenditures'),
    Sections(title: 'Section 104', description: 'Prohibited donations by candidates, treasurers of parties or their agents'),
    Sections(title: 'Section 105', description: 'Accounting  by  agents  of  candidate  or  treasurer'),
    Sections(title: 'Section 106', description: 'Records of contributions and expenditures'),
    Sections(title: 'Section 107', description: 'Statement  of  contributions  and  expenditures'),
    Sections(title: 'Section 108', description: 'Place for filing statements'),
    Sections(title: 'Section 109', description: 'Form and contents of statement'),
    Sections(title: 'Section 110', description: 'Preservation and inspection of statements'),
    Sections(title: 'Section 111', description: 'Effect  of  failure  to  file  statement'),
    Sections(title: 'Section 112', description: 'Report of contractor and business firms'),
    Sections(title: 'Section 113', description: 'Permanent  List  of  Voter'),
    Sections(title: 'Section 114', description: 'Renewal of the Permanent List'),
    Sections(title: 'Section 115', description: 'Necessity  of  Registration'),
    Sections(title: 'Section 116', description: 'Who may be registered in the list'),
    Sections(title: 'Section 117', description: 'Qualifications of a voter'),
    Sections(title: 'Section 118', description: 'Disqualifications'),
    Sections(title: 'Section 119', description: 'Preparation  of  the  permanent  list  of  voters'),
    Sections(title: 'Section 120', description: 'Preparation  of  the  list  before  other  regular  elections'),
    Sections(title: 'Section 121', description: 'Preparation of the list before any special election, plebiscite or referendum'),
    Sections(title: 'Section 122', description: 'Transfer of names of voters from the permanent list to the current one'),
    Sections(title: 'Section 123', description: 'Cancellation and exclusion in the transfer of names'),
    Sections(title: 'Section 124', description: 'Meeting to close the list of voters'),
    Sections(title: 'Section 125', description: 'Re-registration'),
    Sections(title: 'Section 126', description: 'Registration of voters'),
    Sections(title: 'Section 127', description: 'Illiterate or disabled applicants'),
    Sections(title: 'Section 128', description: "Voter's identification"),
    Sections(title: 'Section 129', description: 'Action by the board of election inspectors'),
    Sections(title: 'Section 130', description: 'Provincial central file of registered voters'),
    Sections(title: 'Section 131', description: 'National central file of registered voters'),
    Sections(title: 'Section 132', description: "Preservation of voter's affidavits"),
    Sections(title: 'Section 133', description: 'Columns in the list of voters'),
    Sections(title: 'Section 134', description: 'Certificate  of  the  board  of  election  inspectors  in  the  list  of  voters'),
    Sections(title: 'Section 135', description: 'Publication of the list'),
    Sections(title: 'Section 136', description: 'Challenge  of  right  to  register'),
    Sections(title: 'Section 137', description: 'Power of the board of election inspectors to administer oaths and issue summons'),
    Sections(title: 'Section 138', description: 'Jurisdiction in inclusion and exclusion cases'),
    Sections(title: 'Section 139', description: 'Petition  for  inclusion  of  voters  in  the  list'),
    Sections(title: 'Section 140', description: 'Voters excluded through inadvertence or registered with an erroneous or misspelled name'),
    Sections(title: 'Section 141', description: 'Change of name of registered voter'),
    Sections(title: 'Section 142', description: 'Petition for exclusion of voters from the list'),
    Sections(title: 'Section 143', description: 'Common rules governing judicial proceedings in the matter of inclusion, exclusion, and correction of names of voters'),
    Sections(title: 'Section 144', description: 'Canvass  to  check  registration'),
    Sections(title: 'Section 145', description: 'Annulment  of  permanent  lists  of  voters'),
    Sections(title: 'Section 146', description: 'Reconstitution  of  lost  or  destroyed  registration  records'),
    Sections(title: 'Section 147', description: 'Examination of registration records'),
    Sections(title: 'Section 148', description: 'List of voters'),
    Sections(title: 'Section 149', description: 'Precincts  and  their  establishment'),
    Sections(title: 'Section 150', description: 'Arrangements of election precincts'),
    Sections(title: 'Section 151', description: 'Publication  of  maps  or  precincts'),
    Sections(title: 'Section 152', description: 'Polling place'),
    Sections(title: 'Section 153', description: 'Designation  of  polling  places'),
    Sections(title: 'Section 154', description: 'Requirements for polling places'),
    Sections(title: 'Section 155', description: 'Building that shall not be used as polling places'),
    Sections(title: 'Section 156', description: 'Signs and flags of polling places'),
    Sections(title: 'Section 157', description: 'Arrangement and contents of polling places'),
    Sections(title: 'Section 158', description: 'Voting booth'),
    Sections(title: 'Section 159', description: 'Guard rails'),
    Sections(title: 'Section 160', description: 'Ballot boxes'),
    Sections(title: 'Section 161', description: 'Tally boards'),
    Sections(title: 'Section 162', description: 'Furnishing  of  ballot  boxes,  forms,  stationeries  and  materials  for  election'),
    Sections(title: 'Section 163', description: 'Inspection of polling places'),
    Sections(title: 'Section 164', description: 'Composition and appointment of board of election inspectors'),
    Sections(title: 'Section 165', description: 'Oath  of  the  members  of  the  board  of  election  inspectors'),
    Sections(title: 'Section 166', description: 'Qualification of members of the board of election inspectors'),
    Sections(title: 'Section 167', description: 'Disqualification'),
    Sections(title: 'Section 168', description: 'Powers of the board of election inspectors'),
    Sections(title: 'Section 169', description: 'Voting  privilege  of  members  of  board  of  election  inspectors'),
    Sections(title: 'Section 170', description: 'Relief and substitution of members of the board of election inspectors'),
    Sections(title: 'Section 171', description: 'Vacancy in the board of election inspectors'),
    Sections(title: 'Section 172', description: 'Proceedings of the board of election inspectors'),
    Sections(title: 'Section 173', description: 'Prohibition of political activity'),
    Sections(title: 'Section 174', description: 'Functioning of the board of election inspectors'),
    Sections(title: 'Section 175', description: 'Temporary vacancies'),
    Sections(title: 'Section 176', description: 'Temporary designation of members of the board of election inspectors by watchers'),
    Sections(title: 'Section 177', description: 'Arrest of absent members'),
    Sections(title: 'Section 178', description: 'Official watchers of candidates'),
    Sections(title: 'Section 179', description: 'Rights  and  duties  of  watchers'),
    Sections(title: 'Section 180', description: 'Other watchers'),
    Sections(title: 'Section 181', description: 'Official ballots'),
    Sections(title: 'Section 182', description: 'Emergency ballots'),
    Sections(title: 'Section 183', description: 'Requisition of official ballots and election returns'),
    Sections(title: 'Section 184', description: 'Printing  of  official  ballots  and  elections  returns'),
    Sections(title: 'Section 185', description: 'Sample official ballots'),
    Sections(title: 'Section 186', description: 'Distribution of official ballots and election returns'),
    Sections(title: 'Section 187', description: 'Committee  on  printing,  storage,  and  distribution  of  official  ballots  and  election  returns'),
    Sections(title: 'Section 188', description: 'Duties  of  the  committee  on  printing  of  official  ballots  and  election  returns'),
    Sections(title: 'Section 189', description: 'Representatives of the registered political parties in the verification and distribution of official ballots and  election  returns'),
    Sections(title: 'Section 190', description: 'Voting hours'),
    Sections(title: 'Section 191', description: 'Preliminaries to the voting'),
    Sections(title: 'Section 192', description: 'Persons allowed in and around the polling place'),
    Sections(title: 'Section 193', description: 'Order of voting'),
    Sections(title: 'Section 194', description: 'Manner of obtaining ballots'),
    Sections(title: 'Section 195', description: 'Manner of preparing the ballot'),
    Sections(title: 'Section 196', description: 'Preparation of ballots for illiterate and disabled persons'),
    Sections(title: 'Section 197', description: 'Spoiled ballots'),
    Sections(title: 'Section 198', description: 'Voting'),
    Sections(title: 'Section 199', description: 'Challenge of illegal voters'),
    Sections(title: 'Section 200', description: 'Challenge based on certain illegal acts'),
    Sections(title: 'Section 201', description: 'Admission of challenged vote immaterial in criminal proceedings'),
    Sections(title: 'Section 202', description: 'Record of challenges and oaths'),
    Sections(title: 'Section 203', description: 'Minutes of voting and counting of votes'),
    Sections(title: 'Section 204', description: 'Disposition of unused ballots at the close of the voting hours'),
    Sections(title: 'Section 205', description: 'Prohibition of premature announcement of voting'),
    Sections(title: 'Section 206', description: 'Counting to be public and without interruption'),
    Sections(title: 'Section 207', description: 'Excess ballots'),
    Sections(title: 'Section 208', description: 'Marked ballots'),
    Sections(title: 'Section 209', description: 'Compartment for spoiled ballots'),
    Sections(title: 'Section 210', description: 'Manner of counting votes'),
    Sections(title: 'Section 211', description: 'Rules for the appreciation of ballots'),
    Sections(title: 'Section 212', description: 'Election returns'),
    Sections(title: 'Section 213', description: 'Proclamation of the result of the election in the polling place'),
    Sections(title: 'Section 214', description: 'Disposition of election returns'),
    Sections(title: 'Section 215', description: 'Board of election inspectors to issue a certificate of the number of votes polled by the candidates for an  office  to  the  watchers'),
    Sections(title: 'Section 216', description: 'Alterations and corrections in the election returns'),
    Sections(title: 'Section 217', description: 'Delivery of the ballot boxes, keys and election supplies and documents'),
    Sections(title: 'Section 218', description: 'Preservation of the voting record'),
    Sections(title: 'Section 219', description: 'Preservation of the ballot boxes, their keys and disposition of their contents'),
    Sections(title: 'Section 220', description: 'Documents and articles omitted or erroneously placed inside the ballot box'),
    Sections(title: 'Section 221', description: 'Board of canvassers'),
    Sections(title: 'Section 222', description: 'Relationship with candidates and other members'),
    Sections(title: 'Section 223', description: 'Prohibition  against  leaving  official  station'),
    Sections(title: 'Section 224', description: 'Feigned illness'),
    Sections(title: 'Section 225', description: 'Vote required'),
    Sections(title: 'Section 226', description: 'Incapacity and substitution of members of boards of canvassers'),
    Sections(title: 'Section 227', description: 'Supervision and control over board of canvassers'),
    Sections(title: 'Section 228', description: 'Notice of meeting of the board'),
    Sections(title: 'Section 229', description: 'Manner of delivery and transmittal of election returns'),
    Sections(title: 'Section 230', description: 'Safekeeping of transmitted election returns'),
    Sections(title: 'Section 231', description: 'Canvass by the board'),
    Sections(title: 'Section 232', description: 'Persons not allowed inside the canvassing room'),
    Sections(title: 'Section 233', description: 'When the election returns are delayed, lost or destroyed'),
    Sections(title: 'Section 234', description: 'Material defects in the election returns'),
    Sections(title: 'Section 235', description: 'When election returns appear to be tampered with or falsified'),
    Sections(title: 'Section 236', description: 'Discrepancies in election returns'),
    Sections(title: 'Section 237', description: 'When  integrity  of  ballots  is  violated'),
    Sections(title: 'Section 238', description: 'Canvass of remaining or unquestioned returns to continue'),
    Sections(title: 'Section 239', description: 'Watchers'),
    Sections(title: 'Section 240', description: 'Election resulting in tie'),
    Sections(title: 'Section 241', description: 'Definition'),
    Sections(title: 'Section 242', description: "Commission's  exclusive  jurisdiction  of  all  pre-proclamation  controversies"),
    Sections(title: 'Section 243', description: 'Issues that may be raised in pre-proclamation controversy.'),
    Sections(title: 'Section 244', description: 'Contested composition or proceedings of the board'),
    Sections(title: 'Section 245', description: 'Contested election returns'),
    Sections(title: 'Section 246', description: 'Summary  proceedings  before  the  Commission'),
    Sections(title: 'Section 247', description: 'Partial  proclamation'),
    Sections(title: 'Section 248', description: 'Effect of filing petition to annual or to suspend the proclamation'),
    Sections(title: 'Section 249', description: 'Jurisdiction of the Commission'),
    Sections(title: 'Section 250', description: 'Election  contests  for  Batasang  Pambansa,  regional,  provincial  and  city  offices'),
    Sections(title: 'Section 251', description: 'Election contests for municipal offices'),
    Sections(title: 'Section 252', description: 'Election contest for barangay offices'),
    Sections(title: 'Section 253', description: 'Petition  for  quo  warranto'),
    Sections(title: 'Section 254', description: 'Procedure in election contests'),
    Sections(title: 'Section 255', description: 'Judicial counting of votes in election'),
    Sections(title: 'Section 256', description: 'Appeals'),
    Sections(title: 'Section 257', description: 'Decision in the Commission'),
    Sections(title: 'Section 258', description: 'Preferential  disposition  of  contests  in  courts'),
    Sections(title: 'Section 259', description: 'Actual or compensatory damages'),
    Sections(title: 'Section 260', description: 'Notice of decisions'),
    Sections(title: 'Section 261', description: 'Prohibited Acts'),
    Sections(title: 'Section 262', description: 'Other election offenses'),
    Sections(title: 'Section 263', description: 'Persons criminally liable'),
    Sections(title: 'Section 264', description: 'Penalties'),
    Sections(title: 'Section 265', description: 'Prosecution'),
    Sections(title: 'Section 266', description: 'Arrest in connection with the election campaign'),
    Sections(title: 'Section 267', description: 'Prescription'),
    Sections(title: 'Section 268', description: 'Jurisdiction of courts'),
    Sections(title: 'Section 269', description: 'Preferential  disposition  of  election  offenses'),
    Sections(title: 'Section 270', description: 'Collection of legal fees'),
    Sections(title: 'Section 271', description: 'Payment of Fees'),
    Sections(title: 'Section 272', description: 'Pending actions'),
    Sections(title: 'Section 273', description: 'Designation of certain pre-election acts immediately after the approval of this Code'),
    Sections(title: 'Section 274', description: 'Accreditation of dominant opposition party'),
    Sections(title: 'Section 275', description: 'Party  representatives  in  the  board  of  election  inspectors'),
    Sections(title: 'Section 276', description: 'Appropriations,  and  insurance  for  board  of  election  inspectors'),
    Sections(title: 'Section 277', description: 'Special election for President before 1987'),
    Sections(title: 'Section 278', description: 'Special election to fill existing vacancies in the Batasang Pambansa'),
    Sections(title: 'Section 279', description: 'Elective  officials  in  existing  sub-provinces'),
    Sections(title: 'Section 280', description: 'Reorganization of the Commission on Elections'),
    Sections(title: 'Section 281', description: 'Separability clause'),
    Sections(title: 'Section 282', description: 'Repealing clause'),
    Sections(title: 'Section 283', description: 'Effectivity'),
  ];

  static List contentRoutes = const [
    Statutory1(),
    Statutory2(),
    Statutory3(),
    Statutory4(),
    Statutory5(),
    Statutory6(),
    Statutory7(),
    Statutory8(),
    Statutory9(),
    Statutory10(),
    Statutory11(),
    Statutory12(),
    Statutory13(),
    Statutory14(),
    Statutory15(),
    Statutory16(),
    Statutory17(),
    Statutory18(),
    Statutory19(),
    Statutory20(),
    Statutory21(),
    Statutory22(),
    Statutory23(),
    Statutory24(),
    Statutory25(),
    Statutory26(),
    Statutory27(),
    Statutory28(),
    Statutory29(),
    Statutory30(),
    Statutory31(),
    Statutory32(),
    Statutory33(),
    Statutory34(),
    Statutory35(),
    Statutory36(),
    Statutory37(),
    Statutory38(),
    Statutory39(),
    Statutory40(),
    Statutory41(),
    Statutory42(),
    Statutory43(),
    Statutory44(),
    Statutory45(),
    Statutory46(),
    Statutory47(),
    Statutory48(),
    Statutory49(),
    Statutory50(),
    Statutory51(),
    Statutory51(),
    Statutory52(),
    Statutory53(),
    Statutory54(),
    Statutory55(),
    Statutory56(),
    Statutory57(),
    Statutory58(),
    Statutory59(),
    Statutory60(),
    Statutory61(),
    Statutory62(),
    Statutory63(),
    Statutory64(),
    Statutory65(),
    Statutory66(),
    Statutory67(),
    Statutory68(),
    Statutory69(),
    Statutory70(),
    Statutory71(),
    Statutory72(),
    Statutory73(),
    Statutory74(),
    Statutory75(),
    Statutory76(),
    Statutory77(),
    Statutory78(),
    Statutory79(),
    Statutory80(),
    Statutory81(),
    Statutory82(),
    Statutory83(),
    Statutory84(),
    Statutory85(),
    Statutory86(),
    Statutory87(),
    Statutory88(),
    Statutory89(),
    Statutory90(),
    Statutory91(),
    Statutory92(),
    Statutory93(),
    Statutory94(),
    Statutory95(),
    Statutory96(),
    Statutory97(),
    Statutory98(),
    Statutory99(),
    Statutory100(),
    Statutory101(),
    Statutory102(),
    Statutory103(),
    Statutory104(),
    Statutory105(),
    Statutory106(),
    Statutory107(),
    Statutory108(),
    Statutory109(),
    Statutory110(),
    Statutory112(),
    Statutory113(),
    Statutory114(),
    Statutory115(),
    Statutory116(),
    Statutory117(),
    Statutory118(),
    Statutory119(),
    Statutory120(),
    Statutory121(),
    Statutory122(),
    Statutory123(),
    Statutory124(),
    Statutory125(),
    Statutory126(),
    Statutory127(),
    Statutory128(),
    Statutory129(),
    Statutory130(),
    Statutory131(),
    Statutory132(),
    Statutory133(),
    Statutory134(),
    Statutory135(),
    Statutory136(),
    Statutory137(),
    Statutory138(),
    Statutory139(),
    Statutory140(),
    Statutory141(),
    Statutory142(),
    Statutory143(),
    Statutory144(),
    Statutory145(),
    Statutory146(),
    Statutory147(),
    Statutory148(),
    Statutory149(),
    Statutory150(),
    Statutory151(),
    Statutory152(),
    Statutory153(),
    Statutory154(),
    Statutory155(),
    Statutory156(),
    Statutory157(),
    Statutory158(),
    Statutory159(),
    Statutory160(),
    Statutory161(),
    Statutory162(),
    Statutory163(),
    Statutory164(),
    Statutory165(),
    Statutory166(),
    Statutory167(),
    Statutory168(),
    Statutory169(),
    Statutory170(),
    Statutory171(),
    Statutory172(),
    Statutory173(),
    Statutory174(),
    Statutory175(),
    Statutory176(),
    Statutory177(),
    Statutory178(),
    Statutory179(),
    Statutory180(),
    Statutory181(),
    Statutory182(),
    Statutory183(),
    Statutory184(),
    Statutory185(),
    Statutory186(),
    Statutory187(),
    Statutory188(),
    Statutory189(),
    Statutory190(),
    Statutory191(),
    Statutory192(),
    Statutory193(),
    Statutory194(),
    Statutory195(),
    Statutory196(),
    Statutory197(),
    Statutory198(),
    Statutory199(),
    Statutory200(),
    Statutory201(),
    Statutory202(),
    Statutory203(),
    Statutory204(),
    Statutory205(),
    Statutory206(),
    Statutory207(),
    Statutory208(),
    Statutory209(),
    Statutory210(),
    Statutory211(),
    Statutory212(),
    Statutory213(),
    Statutory214(),
    Statutory215(),
    Statutory216(),
    Statutory217(),
    Statutory218(),
    Statutory219(),
    Statutory220(),
    Statutory221(),
    Statutory222(),
    Statutory223(),
    Statutory224(),
    Statutory225(),
    Statutory226(),
    Statutory227(),
    Statutory228(),
    Statutory229(),
    Statutory230(),
    Statutory231(),
    Statutory232(),
    Statutory233(),
    Statutory234(),
    Statutory235(),
    Statutory236(),
    Statutory237(),
    Statutory238(),
    Statutory239(),
    Statutory240(),
    Statutory241(),
    Statutory242(),
    Statutory243(),
    Statutory244(),
    Statutory245(),
    Statutory246(),
    Statutory247(),
    Statutory248(),
    Statutory249(),
    Statutory250(),
    Statutory251(),
    Statutory252(),
    Statutory253(),
    Statutory254(),
    Statutory255(),
    Statutory256(),
    Statutory257(),
    Statutory258(),
    Statutory259(),
    Statutory260(),
    Statutory261(),
    Statutory262(),
    Statutory263(),
    Statutory262(),
    Statutory264(),
    Statutory265(),
    Statutory266(),
    Statutory267(),
    Statutory268(),
    Statutory269(),
    Statutory270(),
    Statutory271(),
    Statutory272(),
    Statutory273(),
    Statutory274(),
    Statutory275(),
    Statutory276(),
    Statutory277(),
    Statutory278(),
    Statutory279(),
    Statutory280(),
    Statutory281(),
    Statutory282(),
    Statutory283(),
  ];

  static List articleRoutes = const [
    SectionStatu1(),
    SectionStatu2(),
    SectionStatu3(),
    SectionStatu4(),
    SectionStatu5(),
    SectionStatu6(),
    SectionStatu7(),
    SectionStatu8(),
    SectionStatu9(),
    SectionStatu10(),
    SectionStatu11(),
    SectionStatu12(),
    SectionStatu13(),
    SectionStatu14(),
    SectionStatu15(),
    SectionStatu16(),
    SectionStatu17(),
    SectionStatu18(),
    SectionStatu19(),
    SectionStatu20(),
    SectionStatu21(),
    SectionStatu22(),
    SectionStatu23(),
    SectionStatu24(),
    SectionStatu25(),
  ];
}