import 'package:legalease_matrimonial/src/pages/contents/categories_contents/categories_sections/statutory_rights/republic_8424/statutory_1-13.dart';

import 'inchoate_sections.dart';

// republic act 8424
class ListOfSectionsStatutory {
  static List<Sections> statutorySection = [
    Sections(title: 'Section 1', description: 'Definition of Terms'),
    Sections(title: 'Section 2', description: 'Accreditation of non-stock, non-profit corporations/NGOs by the Accrediting Entity'),
    Sections(title: 'Section 3', description: 'Donations to Accredited Non-stock, Non-profit Corporations/NGOs'),
    Sections(title: 'Section 4', description: 'Utilization Requirements'),
    Sections(title: 'Section 5', description: 'Certificate of Donations'),
    Sections(title: 'Section 6', description: 'Notice of Donations'),
    Sections(title: 'Section 7', description: 'Date and Place of Filing Returns'),
    Sections(title: 'Section 8', description: 'Substantiation Requirements'),
    Sections(title: 'Section 9', description: 'Monitoring and Verification of Annual Information Return'),
    Sections(title: 'Section 10', description: 'Prohibited Transactions'),
    Sections(title: 'Section 11', description: 'Withdrawal of Certificate of Accreditation and Revocation of the Certificate of Registration'),
    Sections(title: 'Section 12', description: 'Repealing Clause'),
    Sections(title: 'Section 13', description: 'Effectivity'),
  ];

}

class ListOfRoutesStatutory {
  static List statutoryRoutes = const [
    StatutoryOne(),
    StatutoryTwo(),
    StatutoryThree(),
    StatutoryFour(),
    StatutoryFive(),
    StatutorySix(),
    StatutorySeven(),
    StatutoryEight(),
    StatutoryNine(),
    StatutoryTen(),
    StatutoryEleven(),
    StatutoryTwelve(),
    StatutoryThirteen(),
  ];
}


// republic act 881
class ListOfArticlesStatutory {
  static List<Sections> listArticles = [
    Sections(title: 'Aricle I', description: 'GENERAL PROVISIONS'),
    Sections(title: 'Aricle II', description: 'ELECTION OF PRESIDENT AND VICE-PRESIDENT'),
    Sections(title: 'Aricle III', description: 'ELECTION OF MEMBERS OF THE BATASANG PAMBANSA'),
    Sections(title: 'Aricle IV', description: 'ELECTION OF LOCAL OFFICIALS'),
    Sections(title: 'Aricle V', description: 'ELECTION OF MEMBERS OF THE REGIONAL ASSEMBLY OF THE AUTONOMOUS REGIONS'),
    Sections(title: 'Aricle VI', description: 'ELECTION OF BARANGAY OFFICIALS'),
    Sections(title: 'Aricle VII', description: 'THE COMMISSION ON ELECTIONS'),
    Sections(title: 'Aricle VIII', description: 'POLITICAL PARTIES'),
    Sections(title: 'Aricle IX', description: 'ELIGIBILITY OF CANDIDATES AND CERTIFICATE OF CANDIDACY'),
    Sections(title: 'Aricle X', description: 'CAMPAIGN AND ELECTION PROPAGANDA'),
    Sections(title: 'Aricle XI', description: 'ELECTORAL CONTRIBUTIONS AND EXPENDITURES'),
    Sections(title: 'Aricle XII', description: 'REGISTRATION OF VOTERS'),
    Sections(title: 'Aricle XIII', description: 'PRECINCTS AND POLLING PLACES'),
    Sections(title: 'Aricle XIV', description: 'BOARD OF ELECTION INSPECTORS'),
    Sections(title: 'Aricle XV', description: 'WATCHERS'),
    Sections(title: 'Aricle XVI', description: 'OFFICIAL BALLOTS AND ELECTION RETURNS'),
    Sections(title: 'Aricle XVII', description: 'CASTING OF VOTES'),
    Sections(title: 'Aricle XVIII', description: 'COUNTING OF VOTES'),
    Sections(title: 'Aricle XIX', description: 'CANVASS AND PROCLAMATION'),
    Sections(title: 'Aricle XX', description: 'PRE-PROCLAMATION CONTROVERSIES'),
    Sections(title: 'Aricle XXI', description: 'ELECTION CONTESTS'),
    Sections(title: 'Aricle XXII', description: 'ELECTION OFFENSES'),
    Sections(title: 'Aricle XXIII', description: 'LEGAL FEES'),
    Sections(title: 'Aricle XXIV', description: 'TRANSITORY PROVISIONS'),
    Sections(title: 'Aricle XXV', description: 'FINAL PROVISIONS'),
  ];


  static List<Sections> sections881 = [
    Sections(title: 'Section 1', description: ''),
    Sections(title: 'Section 2', description: ''),
    Sections(title: 'Section 3', description: ''),
    Sections(title: 'Section 4', description: ''),
    Sections(title: 'Section 5', description: ''),
    Sections(title: 'Section 6', description: ''),
    Sections(title: 'Section 7', description: ''),
    Sections(title: 'Section 8', description: ''),
    Sections(title: 'Section 9', description: ''),
    Sections(title: 'Section 10', description: ''),
    Sections(title: 'Section 11', description: ''),
    Sections(title: 'Section 12', description: ''),
    Sections(title: 'Section 13', description: ''),
    Sections(title: 'Section 14', description: ''),
    Sections(title: 'Section 15', description: ''),
    Sections(title: 'Section 16', description: ''),
    Sections(title: 'Section 17', description: ''),
    Sections(title: 'Section 18', description: ''),
    Sections(title: 'Section 19', description: ''),
    Sections(title: 'Section 20', description: ''),
    Sections(title: 'Section 21', description: ''),
    Sections(title: 'Section 22', description: ''),
    Sections(title: 'Section 23', description: ''),
    Sections(title: 'Section 24', description: ''),
    Sections(title: 'Section 25', description: ''),
    Sections(title: 'Section 26', description: ''),
    Sections(title: 'Section 27', description: ''),
    Sections(title: 'Section 28', description: ''),
    Sections(title: 'Section 29', description: ''),
    Sections(title: 'Section 30', description: ''),
    Sections(title: 'Section 31', description: ''),
    Sections(title: 'Section 32', description: ''),
    Sections(title: 'Section 33', description: ''),
    Sections(title: 'Section 34', description: ''),
    Sections(title: 'Section 35', description: ''),
    Sections(title: 'Section 36', description: ''),
    Sections(title: 'Section 37', description: ''),
    Sections(title: 'Section 38', description: ''),
    Sections(title: 'Section 39', description: ''),
    Sections(title: 'Section 40', description: ''),
    Sections(title: 'Section 41', description: ''),
    Sections(title: 'Section 42', description: ''),
    Sections(title: 'Section 43', description: ''),
    Sections(title: 'Section 44', description: ''),
    Sections(title: 'Section 45', description: ''),
    Sections(title: 'Section 46', description: ''),
    Sections(title: 'Section 47', description: ''),
    Sections(title: 'Section 48', description: ''),
    Sections(title: 'Section 49', description: ''),
    Sections(title: 'Section 50', description: ''),
    Sections(title: 'Section 51', description: ''),
    Sections(title: 'Section 52', description: ''),
    Sections(title: 'Section 53', description: ''),
    Sections(title: 'Section 54', description: ''),
    Sections(title: 'Section 55', description: ''),
    Sections(title: 'Section 56', description: ''),
    Sections(title: 'Section 57', description: ''),
    Sections(title: 'Section 58', description: ''),
    Sections(title: 'Section 59', description: ''),
    Sections(title: 'Section 60', description: ''),
    Sections(title: 'Section 61', description: ''),
    Sections(title: 'Section 62', description: ''),
    Sections(title: 'Section 63', description: ''),
    Sections(title: 'Section 64', description: ''),
    Sections(title: 'Section 65', description: ''),
    Sections(title: 'Section 66', description: ''),
    Sections(title: 'Section 67', description: ''),
    Sections(title: 'Section 68', description: ''),
    Sections(title: 'Section 69', description: ''),
    Sections(title: 'Section 70', description: ''),
    Sections(title: 'Section 71', description: ''),
    Sections(title: 'Section 72', description: ''),
    Sections(title: 'Section 73', description: ''),
    Sections(title: 'Section 74', description: ''),
    Sections(title: 'Section 75', description: ''),
    Sections(title: 'Section 76', description: ''),
    Sections(title: 'Section 77', description: ''),
    Sections(title: 'Section 78', description: ''),
    Sections(title: 'Section 79', description: ''),
    Sections(title: 'Section 80', description: ''),
    Sections(title: 'Section 81', description: ''),
    Sections(title: 'Section 82', description: ''),
    Sections(title: 'Section 83', description: ''),
    Sections(title: 'Section 84', description: ''),
    Sections(title: 'Section 85', description: ''),
    Sections(title: 'Section 86', description: ''),
    Sections(title: 'Section 87', description: ''),
    Sections(title: 'Section 88', description: ''),
    Sections(title: 'Section 89', description: ''),
    Sections(title: 'Section 90', description: ''),
    Sections(title: 'Section 91', description: ''),
    Sections(title: 'Section 92', description: ''),
    Sections(title: 'Section 93', description: ''),
    Sections(title: 'Section 94', description: ''),
    Sections(title: 'Section 95', description: ''),
    Sections(title: 'Section 96', description: ''),
    Sections(title: 'Section 97', description: ''),
    Sections(title: 'Section 98', description: ''),
    Sections(title: 'Section 99', description: ''),
    Sections(title: 'Section 100', description: ''),
    Sections(title: 'Section 101', description: ''),
    Sections(title: 'Section 102', description: ''),
    Sections(title: 'Section 103', description: ''),
    Sections(title: 'Section 104', description: ''),
    Sections(title: 'Section 105', description: ''),
    Sections(title: 'Section 106', description: ''),
    Sections(title: 'Section 107', description: ''),
    Sections(title: 'Section 108', description: ''),
    Sections(title: 'Section 109', description: ''),
    Sections(title: 'Section 110', description: ''),
    Sections(title: 'Section 111', description: ''),
    Sections(title: 'Section 112', description: ''),
    Sections(title: 'Section 113', description: ''),
    Sections(title: 'Section 114', description: ''),
    Sections(title: 'Section 115', description: ''),
    Sections(title: 'Section 116', description: ''),
    Sections(title: 'Section 117', description: ''),
    Sections(title: 'Section 118', description: ''),
    Sections(title: 'Section 119', description: ''),
    Sections(title: 'Section 120', description: ''),
    Sections(title: 'Section 121', description: ''),
    Sections(title: 'Section 122', description: ''),
    Sections(title: 'Section 123', description: ''),
    Sections(title: 'Section 124', description: ''),
    Sections(title: 'Section 125', description: ''),
    Sections(title: 'Section 126', description: ''),
    Sections(title: 'Section 127', description: ''),
    Sections(title: 'Section 128', description: ''),
    Sections(title: 'Section 129', description: ''),
    Sections(title: 'Section 130', description: ''),
    Sections(title: 'Section 131', description: ''),
    Sections(title: 'Section 132', description: ''),
    Sections(title: 'Section 133', description: ''),
    Sections(title: 'Section 134', description: ''),
    Sections(title: 'Section 135', description: ''),
    Sections(title: 'Section 136', description: ''),
    Sections(title: 'Section 137', description: ''),
    Sections(title: 'Section 138', description: ''),
    Sections(title: 'Section 139', description: ''),
    Sections(title: 'Section 140', description: ''),
    Sections(title: 'Section 141', description: ''),
    Sections(title: 'Section 142', description: ''),
    Sections(title: 'Section 143', description: ''),
    Sections(title: 'Section 144', description: ''),
    Sections(title: 'Section 145', description: ''),
    Sections(title: 'Section 146', description: ''),
    Sections(title: 'Section 147', description: ''),
    Sections(title: 'Section 148', description: ''),
    Sections(title: 'Section 149', description: ''),
    Sections(title: 'Section 150', description: ''),
    Sections(title: 'Section 151', description: ''),
    Sections(title: 'Section 152', description: ''),
    Sections(title: 'Section 153', description: ''),
    Sections(title: 'Section 154', description: ''),
    Sections(title: 'Section 155', description: ''),
    Sections(title: 'Section 156', description: ''),
    Sections(title: 'Section 157', description: ''),
    Sections(title: 'Section 158', description: ''),
    Sections(title: 'Section 159', description: ''),
    Sections(title: 'Section 160', description: ''),
    Sections(title: 'Section 161', description: ''),
    Sections(title: 'Section 162', description: ''),
    Sections(title: 'Section 163', description: ''),
    Sections(title: 'Section 164', description: ''),
    Sections(title: 'Section 165', description: ''),
    Sections(title: 'Section 166', description: ''),
    Sections(title: 'Section 167', description: ''),
    Sections(title: 'Section 168', description: ''),
    Sections(title: 'Section 169', description: ''),
    Sections(title: 'Section 170', description: ''),
    Sections(title: 'Section 171', description: ''),
    Sections(title: 'Section 172', description: ''),
    Sections(title: 'Section 173', description: ''),
    Sections(title: 'Section 174', description: ''),
    Sections(title: 'Section 175', description: ''),
    Sections(title: 'Section 176', description: ''),
    Sections(title: 'Section 177', description: ''),
    Sections(title: 'Section 178', description: ''),
    Sections(title: 'Section 179', description: ''),
    Sections(title: 'Section 180', description: ''),
    Sections(title: 'Section 181', description: ''),
    Sections(title: 'Section 182', description: ''),
    Sections(title: 'Section 183', description: ''),
    Sections(title: 'Section 184', description: ''),
    Sections(title: 'Section 185', description: ''),
    Sections(title: 'Section 186', description: ''),
    Sections(title: 'Section 187', description: ''),
    Sections(title: 'Section 188', description: ''),
    Sections(title: 'Section 189', description: ''),
    Sections(title: 'Section 190', description: ''),
    Sections(title: 'Section 191', description: ''),
    Sections(title: 'Section 192', description: ''),
    Sections(title: 'Section 193', description: ''),
    Sections(title: 'Section 194', description: ''),
    Sections(title: 'Section 195', description: ''),
    Sections(title: 'Section 196', description: ''),
    Sections(title: 'Section 197', description: ''),
    Sections(title: 'Section 198', description: ''),
    Sections(title: 'Section 199', description: ''),
    Sections(title: 'Section 200', description: ''),
    Sections(title: 'Section 201', description: ''),
    Sections(title: 'Section 202', description: ''),
    Sections(title: 'Section 203', description: ''),
    Sections(title: 'Section 204', description: ''),
    Sections(title: 'Section 205', description: ''),
    Sections(title: 'Section 206', description: ''),
    Sections(title: 'Section 207', description: ''),
    Sections(title: 'Section 208', description: ''),
    Sections(title: 'Section 209', description: ''),
    Sections(title: 'Section 210', description: ''),
    Sections(title: 'Section 211', description: ''),
    Sections(title: 'Section 212', description: ''),
    Sections(title: 'Section 213', description: ''),
    Sections(title: 'Section 214', description: ''),
    Sections(title: 'Section 215', description: ''),
    Sections(title: 'Section 216', description: ''),
    Sections(title: 'Section 217', description: ''),
    Sections(title: 'Section 218', description: ''),
    Sections(title: 'Section 219', description: ''),
    Sections(title: 'Section 220', description: ''),
    Sections(title: 'Section 221', description: ''),
    Sections(title: 'Section 222', description: ''),
    Sections(title: 'Section 223', description: ''),
    Sections(title: 'Section 224', description: ''),
    Sections(title: 'Section 225', description: ''),
    Sections(title: 'Section 226', description: ''),
    Sections(title: 'Section 227', description: ''),
    Sections(title: 'Section 228', description: ''),
    Sections(title: 'Section 229', description: ''),
    Sections(title: 'Section 230', description: ''),
    Sections(title: 'Section 231', description: ''),
    Sections(title: 'Section 232', description: ''),
    Sections(title: 'Section 233', description: ''),
    Sections(title: 'Section 234', description: ''),
    Sections(title: 'Section 235', description: ''),
    Sections(title: 'Section 236', description: ''),
    Sections(title: 'Section 237', description: ''),
    Sections(title: 'Section 238', description: ''),
    Sections(title: 'Section 239', description: ''),
    Sections(title: 'Section 240', description: ''),
    Sections(title: 'Section 241', description: ''),
    Sections(title: 'Section 242', description: ''),
    Sections(title: 'Section 243', description: ''),
    Sections(title: 'Section 244', description: ''),
    Sections(title: 'Section 245', description: ''),
    Sections(title: 'Section 246', description: ''),
    Sections(title: 'Section 247', description: ''),
    Sections(title: 'Section 248', description: ''),
    Sections(title: 'Section 249', description: ''),
    Sections(title: 'Section 250', description: ''),
    Sections(title: 'Section 251', description: ''),
    Sections(title: 'Section 252', description: ''),
    Sections(title: 'Section 253', description: ''),
    Sections(title: 'Section 254', description: ''),
    Sections(title: 'Section 255', description: ''),
    Sections(title: 'Section 256', description: ''),
    Sections(title: 'Section 257', description: ''),
    Sections(title: 'Section 258', description: ''),
    Sections(title: 'Section 259', description: ''),
    Sections(title: 'Section 260', description: ''),
    Sections(title: 'Section 261', description: ''),
    Sections(title: 'Section 262', description: ''),
    Sections(title: 'Section 263', description: ''),
    Sections(title: 'Section 264', description: ''),
    Sections(title: 'Section 265', description: ''),
    Sections(title: 'Section 266', description: ''),
    Sections(title: 'Section 267', description: ''),
    Sections(title: 'Section 268', description: ''),
    Sections(title: 'Section 269', description: ''),
    Sections(title: 'Section 270', description: ''),
    Sections(title: 'Section 271', description: ''),
    Sections(title: 'Section 272', description: ''),
    Sections(title: 'Section 273', description: ''),
    Sections(title: 'Section 274', description: ''),
    Sections(title: 'Section 275', description: ''),
    Sections(title: 'Section 276', description: ''),
    Sections(title: 'Section 277', description: ''),
    Sections(title: 'Section 278', description: ''),
    Sections(title: 'Section 279', description: ''),
    Sections(title: 'Section 280', description: ''),
    Sections(title: 'Section 281', description: ''),
    Sections(title: 'Section 282', description: ''),
    Sections(title: 'Section 283', description: ''),
  ];
}